// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzXVoPA1LGVPZHGYc-aUt1FM8jSfcndcE',
    appId: '1:78829641647:android:db210fe0bd8090847e195a',
    messagingSenderId: '78829641647',
    projectId: 'fir-ijal',
    storageBucket: 'fir-ijal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrMDS_5SV0AmrcWGvIhhf7syEZNCj9P4w',
    appId: '1:78829641647:ios:ae45510e157ca8087e195a',
    messagingSenderId: '78829641647',
    projectId: 'fir-ijal',
    storageBucket: 'fir-ijal.appspot.com',
    androidClientId: '78829641647-lk7upn5bdcrk7vndi1sqqfdr9ffr4ggn.apps.googleusercontent.com',
    iosClientId: '78829641647-g7n1u0l3l71poel4mtj641is4s66th9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.modul3',
  );
}
